### ISSUE TITLE
Schema documentation

### ISSUE THREAD

**Issue by senseibara** [medic/config-msf#10]

**Comment by mouriceb** [comment]
@senseibara , @Fatoufall, do we still need this now that the Niger team will be doing their own dashboards?

**Comment by Fatoufall** [comment]
@mouriceb MSF is improving the UX not the calculation. I think we need to have this document, correct?

**Comment by mouriceb** [comment]
Working on this, will finalize today.
Since they have given a list of data fields that they are using to do their own dashboards I will also have the list of data fields they have requested as part of this.

**Comment by mouriceb** [comment]
This is the working document with the data fields. We will be updating as we build on additional components of the workflows and data needs.

https://docs.google.com/spreadsheets/d/16PbCxCXtQBxpSN7a4vcRuQWYaIUxZ10QsFFA7_JJxsg/edit?ts=5ea803cf#gid=0

**Comment by mouriceb** [comment]
Updated the document with the updated source data fields based on scale up hierarchy and form configs
