### ISSUE TITLE
Updates for contact forms

### ISSUE THREAD

**Issue by kennsippell** [medic/config-msf#101]
Go through the contact forms and make any updates that are necessary. 

For patients:

* Why do the current forms ask for ARV Number before asking if you are ARV patient?
* What does it mean to put ARV=unknown TB=unknown? Should these options exists
* Choose appropriate icons for the contact types in app_settings.json
* There is a requirement that we not capture the birthdate of patients, only the birth month or birth year? Discuss with design and implement.

Remember if you change the person-create form, then you also need to make the same changes in phone_owner:create.

Also need to decide what attributes of a contact are editable? Nothing impacting the RapidPro behaviour can be editable.

- [x] health_center:create
- [x] health_center:edit
- [x] nurse_area:create
- [x] nurse_area:edit
- [x] phone_owner:create
- [x] phone_owner:edit
- [x] patient:create
- [x] patient:edit

**Comment by mmureithi** [comment]
Are there any design requirements pending for this issue?

**Comment by kitsao** [comment]
Maybe not. Closing.
