### ISSUE TITLE
Dashboards design 

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#105]
Outputs: dashboards mockups

**Comment by mmureithi** [comment]
@fatousylla lets touch base with @mouriceb to determine his role in this. My assumption was that he'd take lead on the indicators review and dashboards mock ups documentation.

**Comment by fatousylla** [comment]
@mmureithi It was my assumption too. I have sent an invitation for a catch-up tomorrow. Thanks

**Comment by mouriceb** [comment]
Related to #106 I believe we should also close this?
