### ISSUE TITLE
Setup pollster service for msf-goma

### ISSUE THREAD

**Issue by kitsao** [medic/config-msf#109]
Get pollster up and running for a testing party on **Friday June 19**. Scripts are in `/pollster`
#### Steps
- Download and install miniconda https://docs.conda.io/en/latest/miniconda.html 
- conda create --name pollster python=3.7 
- conda activate pollster 
- pip install -r requirements.txt --no-cache 
- ./run.sh (use updated values shared)

**Comment by nomulex** [comment]
Service is up
