### ISSUE TITLE
Make pollster publicly accessible

### ISSUE THREAD

**Issue by kitsao** [medic/config-msf#111]
This is a step I missed on this ticket #109 . 

- It is so, so that Rapid Pro can relay requests to it, to be forwarded to CHT.
- `run.sh` will then be updated with the access URL

**Comment by kitsao** [comment]
![image](https://user-images.githubusercontent.com/3928714/85111060-7b8eb580-b21c-11ea-8171-189eb9e8bc1c.png)

**Comment by nomulex** [comment]
@kitsao Kindly provide more detail on how  the call back URL is configured.

**Comment by kitsao** [comment]
1. Update pollster's `constants.py` to use `https` instead of `http`. Updated [here](https://github.com/medic/config-msf/blob/medic-pollster/pollster/constants.py).
2. Update `run.sh`, see updated values shared on Slack. Note that pollster will be running on port 9090. Update `HTTP_MY_HOST` to point to the publicly accessible URL. 

   - What I've been doing locally is `./ngrok http 9090` and used the resulting URL.
3. Once updated, start pollster.

**Comment by nomulex** [comment]
After several attempts to expose  the service on a port, I reckon that someone who has more detail about the inner workings of the app takes a stab at this. I am able to dockerize and get the app to run but I am not able to get the app listening on your preferred port 9090. I  think miniconda has a way  of diverting traffic.  Could you dockerize the app and i will be happy to set it up in our k8s infra.  I think @sacul-git could help you with this as I recently set up a similar python app that he dockerized [here](https://github.com/medic/medic-projects/issues/7456).  Here's the dockerfile  that I have been working with.

```# Get Miniconda Image
FROM frolvlad/alpine-miniconda3 

# Set working directory
WORKDIR /usr/src/pollster/
#Add all necessary files
COPY pollster/*   /usr/src/pollster/

RUN conda create --name pollster python=3.7 

# Initialize conda in bash config fiiles:
RUN conda init bash

# Activate the environment:
RUN echo "conda activate pollster" > ~/.bashrc

RUN pip install -r requirements.txt

EXPOSE 9090


ENTRYPOINT ["/bin/sh", "run.sh"]```

**Comment by sacul-git** [comment]
If the issue is just miniconda, it might just be possible to avoid using it with a Dockerfile similar to:

```
FROM python:3.7

# Set working directory
WORKDIR /usr/src/pollster/
#Add all necessary files
COPY pollster/*   /usr/src/pollster/

RUN pip install -r requirements.txt

EXPOSE 9090

ENTRYPOINT ["/bin/sh", "run.sh"]```

```

**Comment by kitsao** [comment]
Hey @nomulex after several discussions, this has been deprioritized/blocked. We'll be testing some updated config that doesn't require pollster. Closing for now.
