### ISSUE TITLE
TB Testing: Scenario 1 (1 patient having treatment issues)

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#122]
You are going to test a 34 years old patient on ARVs and TB treatment. 

The phone owner has to register one patient with this following profile: 

Patient's profile: 

- [ ] ARV treatment:  Yes/No

- [ ] Profile of the ARV treatment: stable/ unstable

- [ ] TB treatment: Yes 

- [ ] Age, gender, location, etc. 

SMS

- [ ] Can you answer questions about Patient's health? Answer 1 to proceed. 

- [ ] Respond 1. Yes to the SMS received on Telegram with the following question: " Is Patient having a problem with TB treatment? Reply 1 for Yes, 2 for No". 

- [ ] SMS received " A health worker will contact you within 1 day. In case of an emergency, please contact your health center."

Expected results: 

- [ ] A task " TB treatment follow up" for the patient will be displayed in the nurse's task tab. 
Current results: 
Please document the following sheet for the testing results https://docs.google.com/spreadsheets/d/1URUEG0B8v3jQ8wqGa7lHKKiM9HlM2gbR/edit#gid=1737066363

**Comment by Fatoufall** [comment]
there a mismatched between patient's name and the summary in the task that displayed another patient's name (phone's holder)
