### ISSUE TITLE
TB Testing: Scenario 2 (Multiple contacts on TB treatment)

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#123]
You are going to test a  scenario of multiple patients (2 or more) with a shared phone number. The 2 patients are in TB treatment and are having issues with their treatment.

The phone owner has to register 2 patients with this following profile:
**Patient 1**
Patient's profile:

 

- [ ] ARV treatment: Yes/No

 

- [ ] Profile of the ARV treatment (if ARV treatment=yes): stable/ unstable

 

- [ ] TB treatment: Yes

 

- [ ] Age, gender, location, etc.

SMS

 

- [ ] Can you answer questions about Patient's health? Answer 1 to proceed.

- [ ] Respond 1. Yes to the SMS received on Telegram with the following question: " Is Patient having a problem with TB treatment? Reply 1 for Yes, 2 for No".

- [ ]  SMS received " A health worker will contact you within 1 day. In case of an emergency, please contact your health center."

- [ ] Expected results:
 A task " TB treatment follow up" for the patient will be displayed in the nurse's task tab.

- [ ] Current results:

Please document the following sheet for the testing results https://docs.google.com/spreadsheets/d/1URUEG0B8v3jQ8wqGa7lHKKiM9HlM2gbR/edit#gid=1737066363
**Patient 2** 

- [ ] Follow the same process as patient 1 by adding another patient under the same number with a different name and age

**Comment by Fatoufall** [comment]
- Tested with 2 phones: 1 with 3 patients and the other with 2 patients. Received all tasks depending on response 1 and end treatment tasks:
Minor issues on french translation
Task's title to fix for Issues with TB treatment
Display only age for the patient's summary in the task

**Comment by boussokane** [comment]
I tested with 2 patients (Doudou and Sokhna). I received all messages (telegram) for both and all tasks.

- The flow still in english 
- Task's title to fix for Issues with TB treatment
- Display only age for the patient's summary in the task. Name, contact number, Household, IDs etc are missing

**Comment by kitsao** [comment]
Update:
- [ ] Minor issues on french translation
- [ ] Task's title to fix for Issues with TB treatment
- [ ] Patient's summary in the task: name, contact number, Household, IDs etc are missing

**Comment by kitsao** [comment]
Updated, ready for testing @fatousylla @boussokane @Fatoufall

**Comment by mmureithi** [comment]
![image](https://user-images.githubusercontent.com/36505554/86758343-78812b00-c04c-11ea-8db5-4479d57c759a.png)


Note: Please refer patient to health assessment.
Should only appear for patients who require health assessment

**Comment by mmureithi** [comment]
![image](https://user-images.githubusercontent.com/36505554/86759647-576d0a00-c04d-11ea-86f6-f05e370028e4.png)

The labels used here are not consistent with what we have in the xls eg. Caregiver

![image](https://user-images.githubusercontent.com/36505554/86760601-01e52d00-c04e-11ea-8185-d27728bb5f1a.png)


The highlighted question should come first. I believe that we have also solved for XX in the SMSes.

What references are we using to update the forms?

**Comment by boussokane** [comment]
I tested with 2 patients : 

- The flow still in english. I switch to french under my user profile and the translation has issus.

**Comment by kitsao** [comment]
Related to #125

**Comment by kitsao** [comment]
Noted @mmureithi
