### ISSUE TITLE
TB Testing: Scenario 3 ( TB ending treatment)

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#124]
You are going to test a scenario of a patient ending his TB treatment. 

The phone owner has to register the patient with this following profile:

Patient's profile:

- [ ] ARV treatment: Yes/No

- [ ] Profile of the ARV treatment (if ARV treatment=yes): stable/ unstable

- [ ] TB treatment: Yes

- [ ] Put the day after the patient creation as the date of the end of his TB treatment

- [ ] Age, gender, location, etc.

SMS

- [ ]  Can you answer questions about Patient's health? Answer 1 to proceed.

- [ ]  Respond 1. Yes to the SMS received on Telegram with the following question: " Is Patient having a problem with TB treatment? Reply 1 for Yes, 2 for No".

 

- [ ] SMS received " A health worker will contact you within 1 day. In case of an emergency, please contact your health center."

- [ ] Expected results:

A task " TB ending treatment " for the patient will be displayed in the nurse's task tab.

- [ ] Current results:

Please document the following sheet for the testing results https://docs.google.com/spreadsheets/d/1URUEG0B8v3jQ8wqGa7lHKKiM9HlM2gbR/edit#gid=1737066363

**Comment by Fatoufall** [comment]
correct for me now
