### ISSUE TITLE
Translations issues

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#125]
Hi team,
We have noted some issues of translation during the testing. We have received text messages in English despite the selected language (French). The CHT app have also the content in English. The translations in French have been revised here: https://docs.google.com/spreadsheets/d/1BOXE_PSNpMz3YDwmqKy6xZN5bD7-SvacOWJUm7B3-W0/edit#gid=689443586

Thanks

**Comment by kitsao** [comment]
I revised the translations, changes uploaded.

**Comment by kitsao** [comment]
@boussokane is working on updating faulty translations (app and tasks), to be ready June 08, 2020

**Comment by Fatoufall** [comment]
the translation for TB issue tasks is still here:
- section empty
sentence on patient's info is wrong and not aligned with XLS
<img width="1189" alt="Capture d’écran 2020-07-07 à 20 01 59" src="https://user-images.githubusercontent.com/35699783/86836478-172d7c00-c08d-11ea-909e-00563db44a1a.png">

**Comment by Fatoufall** [comment]
<img width="722" alt="Capture d’écran 2020-07-07 à 10 24 27" src="https://user-images.githubusercontent.com/35699783/86836745-74c1c880-c08d-11ea-8508-30ce44de4925.png">

**Comment by Fatoufall** [comment]
No title
<img width="720" alt="Capture d’écran 2020-07-07 à 10 24 10" src="https://user-images.githubusercontent.com/35699783/86836805-93c05a80-c08d-11ea-82b9-b6e2a3a64cd9.png">

**Comment by Fatoufall** [comment]
Not aligned with XLS
<img width="721" alt="Capture d’écran 2020-07-07 à 10 25 43" src="https://user-images.githubusercontent.com/35699783/86836942-c4a08f80-c08d-11ea-982e-faabe6bf9d10.png">

**Comment by boussokane** [comment]
<img width="466" alt="Changement" src="https://user-images.githubusercontent.com/53522177/87139992-4eb84600-c290-11ea-84e2-7090b8a5413b.PNG">
