### ISSUE TITLE
Create a task for the follow-up after a sample collection

### ISSUE THREAD

**Issue by senseibara** [medic/config-msf#14]

**Comment by binokaryg** [comment]
A task and form have been added. It has not been finalized and tested yet.

**Comment by fatousylla** [comment]
Hi team, 
MoH Niger is asking about this ticket when could it be implemented. 
Thanks
cc @Fatoufall

**Comment by kennsippell** [comment]
@binokaryg Please let us know if/when you'd like assistance testing the task.

**Comment by binokaryg** [comment]
From the [requirements](https://docs.google.com/spreadsheets/d/1CapXDLhQQEKoQTiK7_ir_vZHDJ7On00udvF9cFAhQAg/edit#gid=1064825956&range=C1:G5):
> This task must appear 12 hours after collection and remain displayed until the task is submitted.

The task due date in CHT only takes the day into account. So, it might be tricky to show the task after 12 hours.
Even if we set it as reported date + 12 hours, the task will show up immediately if the due date falls on today.

**Scenario 1:** 
Reported date = today at 11 AM
Due date = Reported date + 12 hours = today at 11 PM
The task will be considered due as today, and show up immediately before 11 PM.
**Scenario 2:**
Reported date = today at 1 PM
Due date = Reported date + 12 hours = tomorrow at 1 AM
The task will be shown tomorrow starting from 12 AM.

To avoid this confusion, I have set the due date to be the same as the reported date, and the task will always appear immediately. Please let me know if this needs to be changed.

**Comment by binokaryg** [comment]
The task and the follow-up form have been completed and added to [this pull request](https://github.com/medic/config-msf/pull/42).

**Comment by Fatoufall** [comment]
the tasks appears 12h after the reported date but should be 12h after the "Date of Prelevement". I was able to select a date different from the "today"

**Comment by senseibara** [comment]
from what i see it is possible to select a date of prelevement in the past but not in the future, is that right on your test too ? 
If yes then it's fine, even if you pick a date two days before today, the task should still appear on the reported date given the 12h have already passed. 
or maybe i didn't understood well what you are flagging ?

**Comment by Fatoufall** [comment]
yes that is my point but really weird to put a due date in the past here. Agreed, let's keep it as it is.
