### ISSUE TITLE
Implement a action form for creating new cases as investigators

### ISSUE THREAD

**Issue by senseibara** [medic/config-msf#15]
Hierarchy 

SAMU (level 1)
v
RIPOSTE(level 2)
v
INVESTIGATOR (level 3)

This is the scenario that will happen if a patient call the samu 

Currently the SAMU form is submitted at samu level and is replicated to the riposte level, a task is then generated from the samu form for riposte user. And that task submitted at riposte will be replicated to investigator, and a bunch of tasks will be triggered at investigator level from that. 

SAMU form > Riposte Task > Investigator Tasks

There is a scenario where the investigator will find a case in the community so we want them to be able to report it. 

The idea is to make the samu form available at their level while making sure the ownership of the report is setted accordingly

SAMU form > Investigator Tasks

**Comment by binokaryg** [comment]
@senseibara Where can I see the requirements/specs for this contact form?
I don't seem to have the permissions to assign someone in this repo. You can assign this to me if the specs are ready.

**Comment by binokaryg** [comment]
Contact Report (id: contact_report) form has been added to the branch [investigator-case-report-15](https://github.com/medic/config-msf/tree/investigator-case-report-15).
- The form is available at level 3 place.
- The report will be assigned to the primary contact of that place.
- Riposte select field is removed

Please let me know if there are other changes required.
