### ISSUE TITLE
General message configuration

### ISSUE THREAD

**Issue by mmureithi** [medic/config-msf#159]
![image](https://user-images.githubusercontent.com/36505554/87792436-928ceb80-c84c-11ea-9bf3-cc6a533d2ee3.png)
The general follow message should be sent before any check in on patients. Consider including this message in the workflows.

**Comment by kitsao** [comment]
Related to #127

**Comment by kitsao** [comment]
The general information [message](https://docs.google.com/spreadsheets/d/1BOXE_PSNpMz3YDwmqKy6xZN5bD7-SvacOWJUm7B3-W0/edit#gid=257317140) ought to be sent out to all patient groups ahead of the checkin questions.
1. Plug the flow to the patient flow
2. Clean up outbound

**Comment by kitsao** [comment]
Closing. Related to #99, see [notes](https://github.com/medic/config-msf/pull/127#pullrequestreview-453031806).
