### ISSUE TITLE
Implement a contact form for creating new IG area

### ISSUE THREAD

**Issue by senseibara** [medic/config-msf#19]

**Comment by kennsippell** [comment]
Please note that I've implemented a custom IG contact form. I'm leaving this open just to confirm that it is what we are wanting/expecting.

**Comment by kennsippell** [comment]
@fatousylla @Fatoufall Ready for testing on https://msf-niger.app.medicmobile.org/

**Comment by kennsippell** [comment]
![Screenshot from 2020-05-04 15-45-25](https://user-images.githubusercontent.com/9014751/81020795-7b7a5800-8e1e-11ea-8b9f-e53da427dd13.png)

**Comment by fatousylla** [comment]
@kennsippell I have tested it. However, when I log in with the username of the riposte team (dosso), I don't see the tab "contact" to be able to access the IG contact form. Thanks

**Comment by senseibara** [comment]
@fatousylla you can try accessing it through this link in the meantime, will update the permissions 
https://msf-niger.app.medicmobile.org/#/contacts/

**Comment by Fatoufall** [comment]
the link above does not work for me, @fatousylla let us know if you can test.

**Comment by senseibara** [comment]
you need to be logged-in before attempting to open the link, otherwise we will let you know when the permissions is updated.

**Comment by fatousylla** [comment]
@Fatoufall The link is working.

**Comment by Fatoufall** [comment]
glad that you were able to test

**Comment by Fatoufall** [comment]
- Title of the form is still in English "New Investigator Area" - should be translated
- We can see "New personne" activated - if this is intentional there are empty fields when clicking on it (DOB, Last Name) and the title is not translated.

**Comment by Fatoufall** [comment]
How will they create credentials with this form? Having this form only will not allow them to create AS

**Comment by senseibara** [comment]
this is just for creating the places and contacts, we have this ticket for the account management part https://github.com/medic/config-msf/issues/21
