### ISSUE TITLE
Implement Riposte follow-up task generated by SAMU

### ISSUE THREAD

**Issue by senseibara** [medic/config-msf#23]

**Comment by kennsippell** [comment]
Had to work around one easy and one painful issue:

* https://github.com/medic/medic-conf/issues/318
* https://github.com/medic/cht-core/issues/6370

**Comment by senseibara** [comment]
Re-opening because the task should be prefilled with the content of the source report but also allow investigator assignment. 

The xls can. be found here https://docs.google.com/spreadsheets/d/1CapXDLhQQEKoQTiK7_ir_vZHDJ7On00udvF9cFAhQAg/edit#gid=724929481

**Comment by senseibara** [comment]
Re-opening because the task should be prefilled with the content of the source report but also allow investigator assignment. 

The xls can. be found here https://docs.google.com/spreadsheets/d/1CapXDLhQQEKoQTiK7_ir_vZHDJ7On00udvF9cFAhQAg/edit#gid=724929481
