### ISSUE TITLE
Create KlipFolio Account for Niger

### ISSUE THREAD

**Issue by mouriceb** [medic/config-msf#43]
We would like to have a Partner account set up for MoH Niger on Klipfolio to allow for dashboard config.
We currently have only one dashboard but there may be a request for additional dashboards in the  future as the project scales up.

-----
CC: @sacul-git @fatousylla

**Comment by derickl** [comment]
Completed yesterday @mouriceb

**Comment by michaelkohn** [comment]
Just FYI i moved this from Setup to Active and allocated 1 dashboard so that they can start adding users.
