### ISSUE TITLE
To put a summary in the investigation task

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#48]
The investigation task when clicked should show a summary of the info on the associated alert. This way they know what was reported in the alert before they start investigating.

**Comment by kennsippell** [comment]
@senseibara While you're looking at this can you also check out this translation? 
`task.outcome-follow-up.title=Issue` 

Is this an accurate translation for the task?

**Comment by senseibara** [comment]
this is ready to be tested @fatousylla

**Comment by senseibara** [comment]
@kennsippell yes it's accurate, at least that's how it was called by the designer... I suspect Moh would prefer another naming, but this word exist in french too ( if that's what you were flagging)

**Comment by fatousylla** [comment]
Tested and ok
