### ISSUE TITLE
Dashboard: Head map

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#52]
Head map of 

1. Alerts (hospital, samu, csi, investigateur)

1. Suspect cases (alerts with sample collection)

1.  Proposition of positive cases

**Comment by Fatoufall** [comment]
I don't thing this is done cc @maremegaye @mouriceb can you confirm?

**Comment by maremegaye** [comment]
No, this is not done

**Comment by senseibara** [comment]
Re-opening, cc @mouriceb

**Comment by maremegaye** [comment]
@senseibara you can close this. MSF will finally implement it
