### ISSUE TITLE
Implement new hierarchy for the app to be ready to scale

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#53]
Setting up the hierarchy “Centre d’alertes (Riposte)” -> “Equipes d’investigations” for the decentralized regional riposte teams.
Please see the hierarchy at the end of the following document: https://docs.google.com/document/d/1OCc2iWB2TEAWQYFDstO8WENv-ptMLU8M/edit#

**Comment by kennsippell** [comment]
@senseibara Do you have the sufficient information you need to implement this change? What is the plan to deploy this hierarchy change in production?

**Comment by senseibara** [comment]
@kennsippell right now we are holding this issues in the backlog following your instructions : 
>We should not making foundational iterations like that until requirements, and actors stabilise slightly.

I cannot say for certain that it might not change in the future, but they gave fairly clear explanation of how they are envisioning this hierarchy in the short/middle term. Yet the pilot is running since 2 days only. Let us know if we can move forward with this and we will plan accordingly.

**Comment by kennsippell** [comment]
Clarifying that comment - my intent was not to dictate priorities, but rather to ensure that we aren't rushing into major reforms after just one day of running a pilot.  The goal of a pilot is to learn and then iterate. My comment was intended to allow time so we can properly deploy and learn from what we have put in place.

It seems likely that future iterations will change the hierarchy, but in my opinion we shouldn't jump into foundational changes after running the pilot for only one day. But the ultimate decision/timing to make changes like that rest with you, the project team.

**Comment by fatousylla** [comment]
@senseibara This has been tested and found to be OK with the new hierarchy.

**Comment by loukmantidjani** [comment]
@senseibara It is OKAY with the new hierarchy.
