### ISSUE TITLE
Tasks not disappears after submission

### ISSUE THREAD

**Issue by Fatoufall** [medic/config-msf#56]
As riposte team, after submitting a task and assign a tracer, it never disappears. On investigator's side, the task appears many time (as many as task re-submitted). Reproduced with riposte1 and not with other users of riposte.

**Comment by kennsippell** [comment]
Product issue - https://github.com/medic/cht-core/issues/6389

**Comment by kennsippell** [comment]
Our current theory is that the above situation is the result of a product bug in 3.8.1 that results if multiple devices login with the same user account. For example, multiple people logged in as `riposte1` on two different machines. Can we give clear guidance to avoid this practice until we can get a core update deployed to mitigate it (no timeline at this point)?

My recommendation to mitigate this is to 

1. Give clear guidance to avoid multiple devices on the same account
1. Fix broken riposte1 user via a new user account riposte11 that we create for them

If this affects more users (not just riposte1 ), let's discuss as other options may be more suitable.

**Comment by kennsippell** [comment]
Closing this and tracking via product issue
