### ISSUE TITLE
Displaying in the task tab of the investigator 

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#60]
Follow-up tasks appear, but without the patient's name or sample number, it is not possible to know to whom the results are reported. 
<img width="952" alt="Bug" src="https://user-images.githubusercontent.com/50739877/80977572-74e6e300-8e14-11ea-8bbc-1917c71f9eb7.png">

**Comment by senseibara** [comment]
this is ready to be tested @fatousylla

**Comment by fatousylla** [comment]
Tested and ok

**Comment by senseibara** [comment]
This may not be the right place for that topic, redirecting you on this issue , and specifically on this comment https://github.com/medic/config-msf/issues/14#issuecomment-623321404 that explains the logic behind that task appearance, we shall continue the discussion there. 

i also don't see any difference between making it 12H after reported date / date de prélévement. 
Giving that date de prélévement cannot be greater than reported date, the task will appear automatically in any case.

**Comment by Fatoufall** [comment]
thanks for the right ticket, just responded that I was able to select date different from reported date. So there is a logic that is not working in the form in all cases
