### ISSUE TITLE
Error in the list of tasks for the investigator

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#61]
Some investigators see tasks from the response (the first 3 tasks) on their task list.

**Comment by kennsippell** [comment]
1. I've gone through the production data for this project to see if this has happened for other users. 
1. I've confirmed that these three tasks (on May 2) are the only riposte_followup tasks to shown to an investigator. 
1. I'm unsure of the exact circumstances which lead to this.
1. I've cleaned up our logic for when riposte tasks should appear. 

I recommend we close this issue but continue to monitor the situation.
