### ISSUE TITLE
Contact form for regional riposte

### ISSUE THREAD

**Issue by senseibara** [medic/config-msf#74]
we should inspire from what was done for investigators

**Comment by fatousylla** [comment]
@senseibara The contact form is not visible at the Regional Riposte interface. The form cannot be seen or accessed.

**Comment by senseibara** [comment]
@fatousylla this is for National riposte to be able to create Regional ripostes. Sorry for the confusion. You should connect as the national riposte to see this

**Comment by fatousylla** [comment]
@senseibara I can see now the contact form when I log in as National riposte. Thanks
