### ISSUE TITLE
Resultat Prevelement task form

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#80]
In the resultat prelevement task form, MoH Niger is requesting to make the second question only show if the first question is positive. 
@loukmantidjani Please can you update the XLS and let @senseibara  know so he can proceed to the configuration. 
Thanks

**Comment by loukmantidjani** [comment]
@fatousylla XLs updated.  
@senseibara https://docs.google.com/spreadsheets/d/1CapXDLhQQEKoQTiK7_ir_vZHDJ7On00udvF9cFAhQAg/edit#gid=1064825956

**Comment by fatousylla** [comment]
@senseibara it is fixed! Thanks

**Comment by senseibara** [comment]
pushed in live instance
