### ISSUE TITLE
MoH Niger: implementation of an investigation form

### ISSUE THREAD

**Issue by fatousylla** [medic/config-msf#91]
MoH wants to implement in the application a form for investigators so that they can fill more fields during their investigation. The requirements of the form have been shared (attach here)
[Fiche_ investigation_KONDA_IBRAHIM.docx](https://github.com/medic/config-msf/files/4757880/Fiche_.investigation_KONDA_IBRAHIM.docx)

Thanks

**Comment by senseibara** [comment]
https://docs.google.com/spreadsheets/d/1CapXDLhQQEKoQTiK7_ir_vZHDJ7On00udvF9cFAhQAg/edit#gid=1246523452
