### ISSUE TITLE
App form changes

### ISSUE THREAD

**Issue by kennsippell** [medic/config-msf#95]
For each app form:

* Go through a design review 
* Never look at the contact document for state, use the computed contact summary as build in #93

- [x] arv_treatment_issues_04
- [x] covid_symptoms_followup_07
- [x] general_followup_01
- [x] no_response_02
- [x] pregnancy_ended_12
- [x] tb_treatment_issues_05
- [ ] covid_followup
- [ ] covid_symptoms_report
- [x] lab_assessment_13
- [x] no_response_request
- [x] support_requested_09
- [x] covid_symptoms_followup_06
- [x] followup_referral_08
- [x] need_drug_supply_03
- [x] patient_forgot_treatment_10
- [x] tb_treatment_ended_11

Feel free to break up this issue into multiple smaller issues for forms that are significant work

**Comment by kitsao** [comment]
Related to #103

**Comment by mmureithi** [comment]
The design documents(forms/taks) have been updated. Reach out if you need any clarification.

**Comment by kitsao** [comment]
The two forms, ` covid_followup` and `covid_symptoms_report` are not part of the [design xls](https://docs.google.com/spreadsheets/d/1Mz8lNOYxYk6AYqhjUazMdQZVCgOu6Lc7wQxh6D-5Igk/edit). If necessary, we'll handle them as a new issue. The rest are good.

**Comment by kitsao** [comment]
Closing this.
